// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDovbIXULnh-zPzK-pgW7PMlHgt8anL30A',
    appId: '1:167274258060:web:a0f14925357d23471765a9',
    messagingSenderId: '167274258060',
    projectId: 'washme-project',
    authDomain: 'washme-project.firebaseapp.com',
    databaseURL: 'https://washme-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'washme-project.appspot.com',
    measurementId: 'G-S7J09TYCJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjikXbwndL5z81Cu9oPaR_nBMZi0PnzUE',
    appId: '1:167274258060:android:c256be247335e3811765a9',
    messagingSenderId: '167274258060',
    projectId: 'washme-project',
    databaseURL: 'https://washme-project-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'washme-project.appspot.com',
  );
}
